name: Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      EXPO_NO_DOCTOR: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      # 1) app.json minimal: aucune image pendant le prebuild (adieu Jimp/CRC)
      - name: Write minimal app.json (no images)
        run: |
          if [ -f app.json ]; then cp app.json app.json.bak || true; fi
          node -e "const fs=require('fs');const j={expo:{name:'Skilldrive',slug:'skilldrive',version:'1.0.0',android:{package:'com.skilldrive.app'}}};fs.writeFileSync('app.json',JSON.stringify(j,null,2));"
          cat app.json

      # 2) Génère le projet natif
      - name: Prebuild (Expo → create android/)
        run: npx expo prebuild -p android

      # 3) Forcer les SDK (tous formats) + AndroidX/Jetifier
      - name: Force Android SDK versions
        run: |
          GP=android/gradle.properties
          touch "$GP"
          # Nouveaux formats
          sed -i '/^android.compileSdk=/d' "$GP" || true
          sed -i '/^android.targetSdk=/d' "$GP" || true
          sed -i '/^android.minSdk=/d' "$GP" || true
          echo 'android.compileSdk=34' >> "$GP"
          echo 'android.targetSdk=34' >> "$GP"
          echo 'android.minSdk=23' >> "$GP"
          # Formats "Version" hérités
          sed -i '/^android.compileSdkVersion=/d' "$GP" || true
          sed -i '/^android.targetSdkVersion=/d' "$GP" || true
          sed -i '/^android.minSdkVersion=/d' "$GP" || true
          echo 'android.compileSdkVersion=34' >> "$GP"
          echo 'android.targetSdkVersion=34' >> "$GP"
          echo 'android.minSdkVersion=23' >> "$GP"
          # AndroidX/Jetifier
          grep -q '^android.useAndroidX=' "$GP" || echo 'android.useAndroidX=true' >> "$GP"
          grep -q '^android.enableJetifier=' "$GP" || echo 'android.enableJetifier=true' >> "$GP"
          # Kotlin toolchain (évite mismatches)
          sed -i '/^kotlin.compiler.execution.strategy=/d' "$GP" || true
          echo 'kotlin.compiler.execution.strategy=in-process' >> "$GP"
          echo "===== android/gradle.properties ====="
          cat "$GP"

          # Fallback dans app/build.gradle
          AB=android/app/build.gradle
          if grep -q 'compileSdkVersion' "$AB"; then
            sed -i 's/compileSdkVersion[[:space:]]\+[0-9]\+/compileSdkVersion 34/' "$AB"
          else
            sed -i '0,/android[[:space:]]*{/{s//android {\n    compileSdkVersion 34/}' "$AB"
          fi
          if grep -q 'minSdkVersion' "$AB"; then
            sed -i 's/minSdkVersion[[:space:]]\+[0-9]\+/minSdkVersion 23/' "$AB"
          else
            sed -i '0,/defaultConfig[[:space:]]*{/{s//defaultConfig {\n        minSdkVersion 23/}' "$AB"
          fi
          if grep -q 'targetSdkVersion' "$AB"; then
            sed -i 's/targetSdkVersion[[:space:]]\+[0-9]\+/targetSdkVersion 34/' "$AB"
          else
            sed -i '0,/defaultConfig[[:space:]]*{/{s//defaultConfig {\n        targetSdkVersion 34/}' "$AB"
          fi

      # 4) ÉPINGLER outillage: Gradle 8.6 + AGP 8.3.2 + Kotlin 1.9.22
      - name: Pin Gradle/AGP/Kotlin versions
        run: |
          # Gradle wrapper 8.6 (plutôt que 8.8)
          WR=android/gradle/wrapper/gradle-wrapper.properties
          sed -i 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.6-all.zip#' "$WR"
          echo "===== gradle-wrapper.properties ====="
          cat "$WR"

          # AGP & Kotlin dans build.gradle (racine)
          RB=android/build.gradle
          # Assure le bloc buildscript.dependencies existe
          if ! grep -q 'buildscript' "$RB"; then
            sed -i '1s;^;buildscript { repositories { google(); mavenCentral() } dependencies { classpath "com.android.tools.build:gradle:8.3.2" classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22" } }\n\n;' "$RB"
          else
            sed -i 's/com\.android\.tools\.build:gradle:[0-9.]\+/com.android.tools.build:gradle:8.3.2/g' "$RB"
            sed -i 's/org\.jetbrains\.kotlin:kotlin-gradle-plugin:[0-9.]\+/org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22/g' "$RB"
            # Si manquants, on les ajoute
            grep -q 'com.android.tools.build:gradle:8.3.2' "$RB" || sed -i 's/buildscript[[:space:]]*{[[:space:]]*repositories[[:space:]]*{[^}]*}[[:space:]]*dependencies[[:space:]]*{[^}]*/&\n        classpath "com.android.tools.build:gradle:8.3.2"\n        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22"/' "$RB"
          fi

          # Kotlin & AGP en catalog (si utilisés) — on neutralise en forçant buildscript ci-dessus.

          echo "===== android/build.gradle (head) ====="
          sed -n '1,120p' "$RB"

      # 5) Nettoyage cache Gradle (au cas où un cache 8.8 resterait)
      - name: Gradle cache cleanup
        run: |
          rm -rf ~/.gradle/caches/*/gradle-8.8*
          rm -rf ~/.gradle/caches/journal-*
          rm -rf ~/.gradle/daemon/
          echo "Caches purgés"

      - name: Gradle permissions
        run: chmod +x android/gradlew

      # 6) Build APK
      - name: Build Debug APK
        run: cd android && ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: skilldrive-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
