name: Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      EXPO_NO_DOCTOR: 1
      EXPO_IMAGE_UTILS_USE_SHARP: "1"   # ⬅️ force Sharp (évite Jimp)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: |
          npm install
          # ⬇️ Installe Sharp pour que Expo utilise Sharp au lieu de Jimp
          npm i --no-audit --no-fund sharp@^0.33

      # ⬇️ Remplace explicitement les images utilisées par Expo par des PNG sains
      - name: Ensure safe Expo assets
        run: |
          mkdir -p assets
          node -e "const fs=require('fs');const b=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==','base64');['icon.png','adaptive-icon.png','splash.png','favicon.png'].forEach(n=>fs.writeFileSync('assets/'+n,b));"
          ls -l assets

      - name: Patch app.json paths (icon/splash/adaptive)
        run: |
          node -e "const fs=require('fs');const p='app.json';const j=JSON.parse(fs.readFileSync(p));j.expo=j.expo||{};j.expo.icon='./assets/icon.png';j.expo.splash={image:'./assets/splash.png',resizeMode:'contain',backgroundColor:'#ffffff'};j.expo.android=j.expo.android||{};j.expo.android.adaptiveIcon={foregroundImage:'./assets/adaptive-icon.png',backgroundColor:'#ffffff'};fs.writeFileSync(p,JSON.stringify(j,null,2));"
          cat app.json

      - name: Prebuild (Expo → crée android/)
        run: |
          rm -rf android
          npx expo prebuild -p android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Debug APK
        run: cd android && ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: skilldrive-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
