name: Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      EXPO_NO_DOCTOR: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      # 1) Prebuild: génère le dossier android/
      - name: Prebuild (Expo → create android/)
        run: npx expo prebuild -p android

      # 2) Patch Gradle: forcer les versions SDK si absentes
      - name: Force Android SDK versions (app/build.gradle)
        run: |
          node -e "const fs=require('fs');const p='android/app/build.gradle';let s=fs.readFileSync(p,'utf8');if(!/compileSdkVersion\\s+\\d+/.test(s)){s=s.replace(/android\\s*\\{/, 'android {\\n    compileSdkVersion 34');}else{s=s.replace(/compileSdkVersion\\s+\\d+/, 'compileSdkVersion 34');}if(!/defaultConfig\\s*\\{[\\s\\S]*minSdkVersion/m.test(s)){s=s.replace(/defaultConfig\\s*\\{/, 'defaultConfig {\\n        minSdkVersion 23\\n        targetSdkVersion 34');}else{s=s.replace(/minSdkVersion\\s+\\d+/, 'minSdkVersion 23');s=s.replace(/targetSdkVersion\\s+\\d+/, 'targetSdkVersion 34');}fs.writeFileSync(p,s);"

      - name: Ensure root build.gradle ext versions (fallback)
        run: |
          node -e "const fs=require('fs');const p='android/build.gradle';let s=fs.readFileSync(p,'utf8');if(!/ext\\s*\\{[\\s\\S]*compileSdkVersion/m.test(s)){s=s.replace(/(buildscript[\\s\\S]*?}\\s*)$/, `$1\next {\\n  buildToolsVersion = \"34.0.0\"\\n  minSdkVersion = 23\\n  compileSdkVersion = 34\\n  targetSdkVersion = 34\\n  kotlinVersion = \"1.9.24\"\\n}\\n`);}fs.writeFileSync(p,s);"

      - name: Gradle permissions
        run: chmod +x android/gradlew

      - name: Build Debug APK
        run: cd android && ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: skilldrive-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
